apiVersion: v1
kind: Service
metadata:
  name: back-end

spec:
  type: ClusterIP
  ports:
    - targetPort: 80 # if not given then port value will be taken
      port: 80  # mandatory field
  selector:
    app: myapp
    tier: frontend
