apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: myapp
    tier: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx
    # - name: busybox
    #   image: busybox