apiVersion: v1
kind: ReplicationController
metadeta:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadeta:
      name: nginx
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3