apiVersion: v1
kind: Service
metadata:
  name: myapp-service

spec:
  type: NodePort
  # type: LoadBalancer
  ports:
    - targetPort: 80 # if not given then port value will be taken
      port: 80  # mandatory field
      nodePort: 30008   # if not given then any free port will be allocated
  selector:
    app: myapp
    tier: frontend
