apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    app: production


# type: ClusterIP and Need to remove nodePort
# type: LoadBalancer works on cloud platform like gcp AWS