apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
rules:
  - apiGroups: [""]
    resources: [""]
    verbs: ["list", "get", "create", "update", "delete"]
    resourceNames: ["blue", "orange"]
      